"""add public_comment to user_route_ratings

Revision ID: 34b576f5a7fe
Revises: c75521d96c65
Create Date: 2026-05-07 18:55:43.353390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b576f5a7fe'
down_revision: Union[str, None] = 'c75521d96c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_route_ratings', sa.Column('public_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_route_ratings', 'public_comment')
    # ### end Alembic commands ###
