"""add username to user

Revision ID: 4e443444fd8d
Revises: 34b576f5a7fe
Create Date: 2026-05-07 22:13:38.211251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e443444fd8d'
down_revision: Union[str, None] = '34b576f5a7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if the column already exists before adding it
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('users')]
    
    if 'username' not in columns:
        op.add_column('users', sa.Column('username', sa.Text(), nullable=True))
        
        # Populate existing users with a default username
        op.execute("UPDATE users SET username = 'hiker_' || substr(id::text, 1, 8) WHERE username IS NULL")
        
        op.alter_column('users', 'username', nullable=False)
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('users')]
    
    if 'username' in columns:
        op.drop_index(op.f('ix_users_username'), table_name='users')
        op.drop_column('users', 'username')
    # ### end Alembic commands ###
