"""create all tables

Revision ID: 8633e2c80096
Revises: 
Create Date: 2026-05-06 16:16:51.292394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8633e2c80096'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('difficulty_rating', sa.Float(), nullable=True),
    sa.Column('rating_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id')
    )
    # op.create_index('idx_canonical_routes_geometry', 'canonical_routes', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('strava_activity_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_polyline', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sport_type', sa.Text(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('moving_time', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reactions_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('canonical_route_id', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_route_id'], ['canonical_routes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_activities_raw_polyline', 'activities', ['raw_polyline'], unique=False, postgresql_using='gist')
    op.create_table('bookmarks',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('canonical_route_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_route_id'], ['canonical_routes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'canonical_route_id')
    )
    op.create_table('comparisons',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('winner_route_id', sa.Integer(), nullable=False),
    sa.Column('loser_route_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loser_route_id'], ['canonical_routes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_route_id'], ['canonical_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('followed_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('strava_accounts',
    sa.Column('strava_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('strava_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_strava_accounts_strava_id'), 'strava_accounts', ['strava_id'], unique=True)
    op.create_table('user_route_ratings',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('canonical_route_id', sa.Integer(), nullable=False),
    sa.Column('rating_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_route_id'], ['canonical_routes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'canonical_route_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_route_ratings')
    op.drop_index(op.f('ix_strava_accounts_strava_id'), table_name='strava_accounts')
    op.drop_table('strava_accounts')
    op.drop_table('follows')
    op.drop_table('comparisons')
    op.drop_table('bookmarks')
    # op.drop_index('idx_activities_raw_polyline', table_name='activities', postgresql_using='gist')
    op.drop_table('activities')
    op.drop_table('users')
    # op.drop_index('idx_canonical_routes_geometry', table_name='canonical_routes', postgresql_using='gist')
    op.drop_table('canonical_routes')
    # ### end Alembic commands ###
