"""add is_admin to user

Revision ID: c75521d96c65
Revises: ce1aaa466ca6
Create Date: 2026-05-07 15:56:15.194730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75521d96c65'
down_revision: Union[str, None] = 'ce1aaa466ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canonical_routes', 'image_url')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.add_column('canonical_routes', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
