"""add_images_column

Revision ID: ce1aaa466ca6
Revises: 371f525cb33d
Create Date: 2026-05-06 21:57:18.557717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1aaa466ca6'
down_revision: Union[str, None] = '371f525cb33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_routes', sa.Column('images', sa.JSON(), nullable=True))
    # op.drop_column('canonical_routes', 'topography_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_routes', sa.Column('topography_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
