"""add_trueskill_columns

Revision ID: f657e81afb86
Revises: 8633e2c80096
Create Date: 2026-05-06 20:29:32.110153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f657e81afb86'
down_revision: Union[str, None] = '8633e2c80096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_routes', sa.Column('rating_mu', sa.Float(), nullable=False, server_default='5.0'))
    op.add_column('canonical_routes', sa.Column('rating_sigma', sa.Float(), nullable=False, server_default='1.5'))
    op.add_column('user_route_ratings', sa.Column('rating_mu', sa.Float(), nullable=False, server_default='5.0'))
    op.add_column('user_route_ratings', sa.Column('rating_sigma', sa.Float(), nullable=False, server_default='1.5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_route_ratings', 'rating_sigma')
    op.drop_column('user_route_ratings', 'rating_mu')
    op.drop_column('canonical_routes', 'rating_sigma')
    op.drop_column('canonical_routes', 'rating_mu')
    # ### end Alembic commands ###
