import React, { useEffect } from 'react';
import { StyleSheet, Text, View, ActivityIndicator, Alert } from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import * as AuthSession from 'expo-auth-session';
import { useRouter } from 'expo-router';
import { Colors } from '../../constants/Colors';

WebBrowser.maybeCompleteAuthSession();

// For local testing, this URI will be generated by Expo
const REDIRECT_URI = AuthSession.makeRedirectUri();

export default function StravaAuth() {
  const router = useRouter();

  useEffect(() => {
    // Auth logic will go here
    const timer = setTimeout(() => {
      Alert.alert("Strava Auth", "Redirecting to Strava...");
      router.back();
    }, 2000);
    return () => clearTimeout(timer);
  }, []);

  return (
    <View style={styles.container}>
      <ActivityIndicator size="large" color={Colors.primary} />
      <Text style={styles.text}>Connecting to Strava...</Text>
      <Text style={styles.subtext}>Redirect: {REDIRECT_URI}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  text: {
    color: Colors.text,
    marginTop: 20,
    fontSize: 18,
    fontWeight: '600',
  },
  subtext: {
    color: Colors.textSecondary,
    marginTop: 10,
    fontSize: 10,
    textAlign: 'center',
  }
});
